name: external_login_interface
description: Interface for external login feature.
version: 0.1.0
homepage: https://github.com/innim/
repository: https://github.com/Innim/flutter_external_login_interface
issue_tracker: https://github.com/Innim/flutter_external_login_interface/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  async: ^2.4.0

dev_dependencies:

flutter:
