name: external_login_interface
description: Interface for external login feature.
version: 0.1.6
homepage: https://github.com/innim/
repository: https://github.com/Innim/flutter_external_login_interface
issue_tracker: https://github.com/Innim/flutter_external_login_interface/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  async: ^2.8.0

flutter:
